#############################################################################
# Makefile for building: CoolCats.app/Contents/MacOS/CoolCats
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  CoolCats.pro
# Template: app
# Command: /Users/agadbois/Qt/5.8/clang_64/bin/qmake -o Makefile CoolCats.pro -spec macx-clang CONFIG+=debug CONFIG+=x86 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/agadbois/Qt/5.8/clang_64/lib
QMAKE         = /Users/agadbois/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CoolCats1.0.0
DISTDIR = /Users/agadbois/Downloads/-include-dad--San_Branch\ 3/-include-dad-/.tmp/CoolCats1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/agadbois/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/agadbois/Qt/5.8/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		loginscreen.cpp \
		users.cpp \
		maininterface.cpp \
		canvas.cpp \
		Circle.cpp \
		Ellipse.cpp \
		Rectangle.cpp \
		shape.cpp \
		Square.cpp \
		line.cpp \
		polyline.cpp \
		maintenancenotes.cpp \
		testimonials.cpp \
		contact.cpp \
		Polygon.cpp \
		help.cpp \
		newnew.cpp \
		textmanip.cpp \
		text.cpp qrc_resources.cpp \
		moc_loginscreen.cpp \
		moc_maininterface.cpp \
		moc_canvas.cpp \
		moc_maintenancenotes.cpp \
		moc_testimonials.cpp \
		moc_contact.cpp \
		moc_help.cpp \
		moc_newnew.cpp
OBJECTS       = main.o \
		loginscreen.o \
		users.o \
		maininterface.o \
		canvas.o \
		Circle.o \
		Ellipse.o \
		Rectangle.o \
		shape.o \
		Square.o \
		line.o \
		polyline.o \
		maintenancenotes.o \
		testimonials.o \
		contact.o \
		Polygon.o \
		help.o \
		newnew.o \
		textmanip.o \
		text.o \
		qrc_resources.o \
		moc_loginscreen.o \
		moc_maininterface.o \
		moc_canvas.o \
		moc_maintenancenotes.o \
		moc_testimonials.o \
		moc_contact.o \
		moc_help.o \
		moc_newnew.o
DIST          = ../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		CoolCats.pro loginscreen.h \
		users.h \
		maininterface.h \
		canvas.h \
		Circle.h \
		Ellipse.h \
		PolyGon.h \
		Rectangle.h \
		shape.h \
		Square.h \
		Vector.h \
		PolyLine.h \
		line.h \
		maintenancenotes.h \
		testimonials.h \
		contact.h \
		help.h \
		newnew.h \
		textmanip.h \
		text.h main.cpp \
		loginscreen.cpp \
		users.cpp \
		maininterface.cpp \
		canvas.cpp \
		Circle.cpp \
		Ellipse.cpp \
		Rectangle.cpp \
		shape.cpp \
		Square.cpp \
		line.cpp \
		polyline.cpp \
		maintenancenotes.cpp \
		testimonials.cpp \
		contact.cpp \
		Polygon.cpp \
		help.cpp \
		newnew.cpp \
		textmanip.cpp \
		text.cpp
QMAKE_TARGET  = CoolCats
DESTDIR       = 
TARGET        = CoolCats.app/Contents/MacOS/CoolCats


first: all
####### Build rules

$(TARGET): ui_loginscreen.h ui_maininterface.h ui_maintenancenotes.h ui_testimonials.h ui_contact.h ui_help.h ui_newnew.h $(OBJECTS)  
	@test -d CoolCats.app/Contents/MacOS/ || mkdir -p CoolCats.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CoolCats.pro ../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.8/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.8/clang_64/mkspecs/features/lex.prf \
		CoolCats.pro \
		resources.qrc \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile CoolCats.pro -spec macx-clang CONFIG+=debug CONFIG+=x86 CONFIG+=qml_debug
../../../Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.8/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.8/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.8/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.8/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.8/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.8/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.8/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.8/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.8/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.8/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.8/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.8/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.8/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.8/clang_64/mkspecs/features/lex.prf:
CoolCats.pro:
resources.qrc:
../../../Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CoolCats.pro -spec macx-clang CONFIG+=debug CONFIG+=x86 CONFIG+=qml_debug

qmake_all: FORCE

CoolCats.app/Contents/PkgInfo: 
	@test -d CoolCats.app/Contents || mkdir -p CoolCats.app/Contents
	@$(DEL_FILE) CoolCats.app/Contents/PkgInfo
	@echo "APPL????" > CoolCats.app/Contents/PkgInfo
CoolCats.app/Contents/Resources/empty.lproj: 
	@test -d CoolCats.app/Contents/Resources || mkdir -p CoolCats.app/Contents/Resources
	@touch CoolCats.app/Contents/Resources/empty.lproj
	
CoolCats.app/Contents/Info.plist: 
	@test -d CoolCats.app/Contents || mkdir -p CoolCats.app/Contents
	@$(DEL_FILE) CoolCats.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.CoolCats,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,CoolCats,g" -e "s,@LIBRARY@,CoolCats,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.8/clang_64/mkspecs/macx-clang/Info.plist.app >CoolCats.app/Contents/Info.plist

all: Makefile \
		CoolCats.app/Contents/PkgInfo \
		CoolCats.app/Contents/Resources/empty.lproj \
		CoolCats.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents loginscreen.h users.h maininterface.h canvas.h Circle.h Ellipse.h PolyGon.h Rectangle.h shape.h Square.h Vector.h PolyLine.h line.h maintenancenotes.h testimonials.h contact.h help.h newnew.h textmanip.h text.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp loginscreen.cpp users.cpp maininterface.cpp canvas.cpp Circle.cpp Ellipse.cpp Rectangle.cpp shape.cpp Square.cpp line.cpp polyline.cpp maintenancenotes.cpp testimonials.cpp contact.cpp Polygon.cpp help.cpp newnew.cpp textmanip.cpp text.cpp $(DISTDIR)/
	$(COPY_FILE) --parents loginscreen.ui maininterface.ui maintenancenotes.ui testimonials.ui contact.ui help.ui newnew.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CoolCats.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../../Qt/5.8/clang_64/bin/rcc \
		fallingleaves.gif \
		MaintenanceNotes.png \
		Inter-Protocol.png \
		CantactUs.png \
		Picstagram.png
	/Users/agadbois/Qt/5.8/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_loginscreen.cpp moc_maininterface.cpp moc_canvas.cpp moc_maintenancenotes.cpp moc_testimonials.cpp moc_contact.cpp moc_help.cpp moc_newnew.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_loginscreen.cpp moc_maininterface.cpp moc_canvas.cpp moc_maintenancenotes.cpp moc_testimonials.cpp moc_contact.cpp moc_help.cpp moc_newnew.cpp
moc_loginscreen.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		users.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		Vector.h \
		maininterface.h \
		maintenancenotes.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		testimonials.h \
		contact.h \
		help.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		Circle.h \
		Ellipse.h \
		Shape.h \
		Square.h \
		Rectangle.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		text.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		loginscreen.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib loginscreen.h -o moc_loginscreen.cpp

moc_maininterface.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		maintenancenotes.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		testimonials.h \
		contact.h \
		help.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		Circle.h \
		Ellipse.h \
		Shape.h \
		Square.h \
		Rectangle.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		text.h \
		users.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		maininterface.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib maininterface.h -o moc_maininterface.cpp

moc_canvas.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		canvas.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib canvas.h -o moc_canvas.cpp

moc_maintenancenotes.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		maintenancenotes.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib maintenancenotes.h -o moc_maintenancenotes.cpp

moc_testimonials.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		testimonials.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib testimonials.h -o moc_testimonials.cpp

moc_contact.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		contact.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib contact.h -o moc_contact.cpp

moc_help.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		help.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib help.h -o moc_help.cpp

moc_newnew.cpp: ../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		users.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		Vector.h \
		maininterface.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		maintenancenotes.h \
		testimonials.h \
		contact.h \
		help.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		Circle.h \
		Ellipse.h \
		Shape.h \
		Square.h \
		Rectangle.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		text.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		newnew.h \
		moc_predefs.h \
		../../../Qt/5.8/clang_64/bin/moc
	/Users/agadbois/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/agadbois/Qt/5.8/clang_64/mkspecs/macx-clang -I'/Users/agadbois/Downloads/-include-dad--San_Branch 3/-include-dad-' -I/Users/agadbois/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/agadbois/Qt/5.8/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -F/Users/agadbois/Qt/5.8/clang_64/lib newnew.h -o moc_newnew.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_loginscreen.h ui_maininterface.h ui_maintenancenotes.h ui_testimonials.h ui_contact.h ui_help.h ui_newnew.h
compiler_uic_clean:
	-$(DEL_FILE) ui_loginscreen.h ui_maininterface.h ui_maintenancenotes.h ui_testimonials.h ui_contact.h ui_help.h ui_newnew.h
ui_loginscreen.h: loginscreen.ui \
		../../../Qt/5.8/clang_64/bin/uic
	/Users/agadbois/Qt/5.8/clang_64/bin/uic loginscreen.ui -o ui_loginscreen.h

ui_maininterface.h: maininterface.ui \
		../../../Qt/5.8/clang_64/bin/uic
	/Users/agadbois/Qt/5.8/clang_64/bin/uic maininterface.ui -o ui_maininterface.h

ui_maintenancenotes.h: maintenancenotes.ui \
		../../../Qt/5.8/clang_64/bin/uic
	/Users/agadbois/Qt/5.8/clang_64/bin/uic maintenancenotes.ui -o ui_maintenancenotes.h

ui_testimonials.h: testimonials.ui \
		../../../Qt/5.8/clang_64/bin/uic
	/Users/agadbois/Qt/5.8/clang_64/bin/uic testimonials.ui -o ui_testimonials.h

ui_contact.h: contact.ui \
		../../../Qt/5.8/clang_64/bin/uic
	/Users/agadbois/Qt/5.8/clang_64/bin/uic contact.ui -o ui_contact.h

ui_help.h: help.ui \
		../../../Qt/5.8/clang_64/bin/uic
	/Users/agadbois/Qt/5.8/clang_64/bin/uic help.ui -o ui_help.h

ui_newnew.h: newnew.ui \
		../../../Qt/5.8/clang_64/bin/uic
	/Users/agadbois/Qt/5.8/clang_64/bin/uic newnew.ui -o ui_newnew.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp newnew.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		users.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		Vector.h \
		maininterface.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		maintenancenotes.h \
		testimonials.h \
		contact.h \
		help.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		Circle.h \
		Ellipse.h \
		Shape.h \
		Square.h \
		Rectangle.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		text.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMovie \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

loginscreen.o: loginscreen.cpp loginscreen.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		users.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		Vector.h \
		maininterface.h \
		maintenancenotes.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		testimonials.h \
		contact.h \
		help.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		Circle.h \
		Ellipse.h \
		Shape.h \
		Square.h \
		Rectangle.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		text.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		ui_loginscreen.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMovie \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginscreen.o loginscreen.cpp

users.o: users.cpp users.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o users.o users.cpp

maininterface.o: maininterface.cpp maininterface.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		maintenancenotes.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		testimonials.h \
		contact.h \
		help.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		Circle.h \
		Ellipse.h \
		Shape.h \
		Square.h \
		Rectangle.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		text.h \
		users.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		ui_maininterface.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSizePolicy \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maininterface.o maininterface.cpp

canvas.o: canvas.cpp canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		Shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cpp

Circle.o: Circle.cpp Circle.h \
		Ellipse.h \
		Shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		canvas.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Circle.o Circle.cpp

Ellipse.o: Ellipse.cpp Ellipse.h \
		Shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		canvas.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ellipse.o Ellipse.cpp

Rectangle.o: Rectangle.cpp Rectangle.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rectangle.o Rectangle.cpp

shape.o: shape.cpp shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shape.o shape.cpp

Square.o: Square.cpp Square.h \
		Rectangle.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Square.o Square.cpp

line.o: line.cpp Line.h \
		Shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		canvas.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		Circle.h \
		Ellipse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o line.o line.cpp

polyline.o: polyline.cpp PolyLine.h \
		Line.h \
		Shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		canvas.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polyline.o polyline.cpp

maintenancenotes.o: maintenancenotes.cpp maintenancenotes.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_maintenancenotes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maintenancenotes.o maintenancenotes.cpp

testimonials.o: testimonials.cpp testimonials.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_testimonials.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testimonials.o testimonials.cpp

contact.o: contact.cpp contact.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_contact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contact.o contact.cpp

Polygon.o: Polygon.cpp PolyGon.h \
		PolyLine.h \
		Line.h \
		Shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		canvas.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Polygon.o Polygon.cpp

help.o: help.cpp help.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o help.o help.cpp

newnew.o: newnew.cpp newnew.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		users.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qvector.h \
		Vector.h \
		maininterface.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		maintenancenotes.h \
		testimonials.h \
		contact.h \
		help.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h \
		Circle.h \
		Ellipse.h \
		Shape.h \
		Square.h \
		Rectangle.h \
		PolyGon.h \
		PolyLine.h \
		Line.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPolygon \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		text.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QSlider \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		ui_newnew.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMovie \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qmovie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newnew.o newnew.cpp

textmanip.o: textmanip.cpp textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textmanip.o textmanip.cpp

text.o: text.cpp text.h \
		shape.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		Vector.h \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		canvas.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		textmanip.h \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/QFont \
		../../../Qt/5.8/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt/5.8/clang_64/lib/QtCore.framework/Headers/qexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o text.o text.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_loginscreen.o: moc_loginscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginscreen.o moc_loginscreen.cpp

moc_maininterface.o: moc_maininterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maininterface.o moc_maininterface.cpp

moc_canvas.o: moc_canvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvas.o moc_canvas.cpp

moc_maintenancenotes.o: moc_maintenancenotes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maintenancenotes.o moc_maintenancenotes.cpp

moc_testimonials.o: moc_testimonials.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testimonials.o moc_testimonials.cpp

moc_contact.o: moc_contact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contact.o moc_contact.cpp

moc_help.o: moc_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_help.o moc_help.cpp

moc_newnew.o: moc_newnew.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newnew.o moc_newnew.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

